### ISSUE TITLE
Is There a way to change volume?

### ISSUE THREAD

**Issue by firdiar-mita** [TLabAltoh/TLabWebView#4]

**Comment by TLabAltoh** [comment]
Hi, currently this plugin does not implement volume change api for webview. You have to use javascript to change the volume of the media. You may find [this forum](https://stackoverflow.com/questions/7582385/is-there-a-way-to-set-the-default-html5-video-volume/21859511#21859511) helpful.

**Comment by firdiar-mita** [comment]
it works, im using youtube iframe, im changing youtube player using EvaluateJs method.
thank you...
