### ISSUE TITLE
Violates Google Security Policy: onReceivedSslError

### ISSUE THREAD

**Issue by firdiar-mita** [TLabAltoh/TLabWebView#8]
I pushed my app to playstore and got this feedback from google

![image](https://github.com/user-attachments/assets/b9807c5f-7654-4a7f-9c35-bdbc39a77b24)
https://support.google.com/faqs/answer/7071387

**Comment by TLabAltoh** [comment]
Perhaps this problem can be solved by removing the override of the corresponding callback or by creating an alert dialog for users such as "Page with invalid ssl certificate, can I open it? (yes/no)". I will work on it.

**Idea 1:** Remove callback to reject by default
```java
/**
 *
 * @param view The WebView that is initiating the callback.
 * @param handler An {@link SslErrorHandler} that will handle the user's
 *            response.
 * @param error The SSL error object.
 */
//@SuppressLint("WebViewClientOnReceivedSslError")
//@Override
//public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
//    handler.proceed();
//}
```

**Idea2:** [Show alert dialog](https://qiita.com/hymmr/items/218e15541191a7a681e4)
```java
/**
 *
 * @param view The WebView that is initiating the callback.
 * @param handler An {@link SslErrorHandler} that will handle the user's
 *            response.
 * @param error The SSL error object.
 */
@Override
public void onReceivedSslError(WebView view, final SslErrorHandler handler, SslError error) {
    AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
    builder.setMessage("Page with invalid ssl certificate, can I open it?");
    builder.setPositiveButton("yes", new DialogInterface.OnClickListener() {
        @Override
        public void onClick(DialogInterface dialog, int which) {
            handler.proceed();
        }
    });
    builder.setNegativeButton("no", new DialogInterface.OnClickListener() {
        @Override
        public void onClick(DialogInterface dialog, int which) {
            handler.cancel();
        }
    });
    builder.setOnKeyListener(new DialogInterface.OnKeyListener() {
        @Override
        public boolean onKey(DialogInterface dialog, int keyCode, KeyEvent event) {
            if (event.getAction() == KeyEvent.ACTION_UP && keyCode == KeyEvent.KEYCODE_BACK) {
                handler.cancel();
                dialog.dismiss();
                return true;
            }
            return false;
        }
    });
    AlertDialog dialog = builder.create();
    dialog.show();
}
```

**Comment by TLabAltoh** [comment]
<video src="https://github.com/user-attachments/assets/edbdf001-7f43-4dde-96b4-0f2917fe4751"></video>

I replaced showing dialog when ssl error occurred (mostly case of self-signed certification) from android's dialog to view based custom dialog. Because the [meta-quest](https://www.meta.com/jp/en/quest/quest-3/?utm_source=gg&utm_medium=ps&utm_campaign=20554172849&utm_term=meta%20quest&utm_content=705918764335&utm_funnel=dcap&gad_source=1&gclid=CjwKCAjw2Je1BhAgEiwAp3KY79HY4-wSb8ZOdx-bX8sZJkCIAEPeQ6PF0k14M59fc5oRvOjl9aee6hoCjQsQAvD_BwE&gclsrc=aw.ds) is one of the target of this plugin, but it can not show android's widget (like dialog, datapicker, etc ...)

**Comment by firdiar-mita** [comment]
im using first option, by not overriding the `onReceivedSslError`
I think in most cases we won't access those non secured website, so that was fine
